### PR TITLE
Update to PHPUnit 6

### PR DESCRIPTION
**Pull request by gabriel-caruso**
As we support `PHP 7`, I've updated our suite of tests to `PHPUnit 6`.

### CODE REVIEW

**Comment by gabriel-caruso** [comment]
@Ocramius Done. I've removed the `--report-useless-tests` command line option, that [was removed in `PHPUnit 6`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#removed).

**Comment by Ocramius** [comment]
What about the strictness of that flag? Was it ported to a config?

**Comment by gabriel-caruso** [comment]
> PHPUnit is now strict about useless tests by default

Source: https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1

**Comment by Ocramius** [comment]
Awesome, thanks!

**Pull request merged**
