### PR TITLE
Allow php 8.3

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by Ocramius** [comment]
@fezfez lock file too, please 😁

**Comment by fezfez** [comment]
> @fezfez lock file too, please 😁

see https://github.com/Roave/infection-static-analysis-plugin/pull/480 before :)

**Comment by Ocramius** [comment]
This can now be adjusted :)

**Comment by fezfez** [comment]
> This can now be adjusted :)

done

**Review by Ocramius — APPROVED** [review]
Thanks @fezfez!

**Pull request merged**
