### PR TITLE
the POST_AUTOLOAD_DUMP event also happens on composer install/update

### PR DESCRIPTION
**Pull request by staabm**
no need to subscribe to install/update and autoload-dump.

fixes https://github.com/Ocramius/PackageVersions/issues/94

### CODE REVIEW

**Comment by staabm** [comment]
my local tests seem to suggest that "composer install" and "composer update" also emit a "post-autoload" event.

tested on composer 1.8.6; php 7.2.6

at best you could verify this on your end

**Comment by Ocramius** [comment]
Thanks @staabm!

**Comment by alcohol** [comment]
What if the user specifies `--no-autoloader`? :thinking:

**Comment by Ocramius** [comment]
Probably would fall back to `FallbackVersions`, which works once `installed.json` and `composer.lock` are there

**Pull request merged**
