### PR TITLE
write VersionClass atomic

### PR DESCRIPTION
**Pull request by SimonHeimberg**
I see two advantages:
 * chmod does not fail when previous file belongs to a different user
 * there is never a partial written file

### CODE REVIEW

**Comment by Ocramius** [comment]
`chmod` should fail when the file is owned by a different user: the problem is just being shifted from `chmod` to `move`.

I get where this patch comes from, but like with previous patches touching this code location, I'd need test automation to verify the scenario.

**Comment by SimonHeimberg** [comment]
Only the file **owner** is allowed to run `chmod`. Write permissions are not sufficient.

**Comment by Ocramius** [comment]
Aha, so the issue is with group ownership. So here's my repeated question: how can we test this in automation?

**Comment by SimonHeimberg** [comment]
What should be tested exactly?

The general functionality of this code is checked in [test/PackageVersionsTest/InstallerTest.php](https://github.com/Ocramius/PackageVersions/blob/master/test/PackageVersionsTest/InstallerTest.php) in `testDumpVersionsClass.*()`. Should I add another test case which first creates a VersionClass file which is not writable or not owned by the current user? Or one emulating full disk while writing VersionClass?

(The issue is with file ownership and chmod.)

**Comment by Ocramius** [comment]
The ownership scenario would be sufficient - atomic write is extremely
tricky to test, although possible by mocking the filesystem.

**Comment by SimonHeimberg** [comment]
How can the test create a file that belongs to another user? Only root is allowed to do chown a file.

**Comment by SimonHeimberg** [comment]
is preventing write (chmod -w) sufficient for the test?

**Comment by Ocramius** [comment]
I think so, yes :+1:

**Comment by Ocramius** [comment]
@mariusklocke the `chmod()` would just be for test purposes, to verify that the write leads to a crash

**Comment by Ocramius** [comment]
Handled in #79

**Pull request closed without merging**
