### PR TITLE
fix composer install --no-dev PHP7

### PR DESCRIPTION
**Pull request by tomcyr**
when using `composer install --no-dev --no-interaction --optimize-autoloader` on PHP7 an error occurred:

```
[ErrorException]                            
  array_merge(): Argument #2 is not an array 
at ocramius/package-versions/src/PackageVersions/Installer.php:187
because $lockData['packages-dev'] = NULL
```

### CODE REVIEW

**Comment by Ocramius** [comment]
The fix looks legit, but a test case backing the change is needed.

**Comment by tomcyr** [comment]
@Ocramius try this method: testDumpVersionsClassNoDev()

**Comment by Ocramius** [comment]
Looks good, thanks!

**Comment by wideawake** [comment]
This is causing a lot of troubles. I solved in all my projects by adding "dev-master" of this package as a project dep (even if other packages was using it).

Can you release it for other people that may occur in this? PHP 7 is such a big improvement so that many other teams will switch to very soon :)

**Comment by Ocramius** [comment]
Yes, a release is due, but we didn't get to do any OSS work lately. @malukenho can you deal with the release of this package today?

**Comment by Ocramius** [comment]
@wideawake released

**Comment by wideawake** [comment]
very good! Thanks.

**Pull request merged**
